version: "3.2"

services:
  backend:
    image: commune/bittensor/backend
    container_name: bittensor-backend
    build: ./
    # entrypoint: ["gunicorn", "--worker-class", "eventlet", "-w", "1", "-b", "0.0.0.0:5000", "--preload", "server.app:app"]
    shm_size: '20gb'
    environment:
      - LOCAL_SUBTENSOR_HOST=subtensor
    ports:
      # - 5000:5000
      - 8501-8505:8501-8505
      - 8080:8080 # 
      - 8266:8265 # ray dashboard 
      # - 7865-7870:7865-7870 # gradio ports
      - 8001:8000 # api
      - 8889:8888 # jupyterlab
    
    # run_options: ["-v", "/home/ubuntu/efs:/efs", "--shm-size=16.89gb"]

    volumes:
      - ./bittensor/bittensor:/app/bittensor/bittensor
      - ./diffusers/src:/app/diffusers/src
      - ./commune:/app/commune
      - ./.bittensor:/root/.bittensor
      - ./scripts:/app/scripts
      - /tmp/wholetensor:/tmp
      - /home/ubuntu/efs:/efs

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]


    command: bash -c "cd /app; chmod +x /app/scripts/*;/app/scripts/startup.sh;"

  