version: "3.2"

services:
  backend:
    image: commune/bittensor/backend
    container_name: backend
    build: ./
    shm_size: '20gb'
    environment:
      - LOCAL_SUBTENSOR_HOST=node-subtensor
    ports:
      # - 5000:5000
      - 8501-8505:8501-8505
      - 8080:8080 # 
      - 8266:8265 # ray dashboard 
      - 7865-7870:7865-7870 # gradio ports
      - 8000:8000 # api
      - 8888:8888 # jupyterlab
    
    # run_options: ["-v", "/home/ubuntu/efs:/efs", "--shm-size=16.89gb"]

    volumes:
      - ./bittensor/bittensor:/app/bittensor/bittensor
      - ./bittensor/tests:/app/bittensor/tests
      - ./diffusers/src:/app/diffusers/src
      - ./commune:/app/commune
      - ./contracts:/app/contracts
      - ./interfaces:/app/interfaces
      - ./artifacts:/app/artifacts
      - ./.bittensor:/root/.bittensor
      - ./scripts:/app/scripts
      - /tmp/wholetensor:/tmp
      - /home/ubuntu/efs:/efs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]


    command: bash -c "cd /app; chmod +x /app/scripts/*;/app/scripts/startup.sh;"

  