version: "3.2"

services:
  backend:
    image: commune/bittensor/backend
    container_name: bittensor-backend
    build: ./
    # entrypoint: ["gunicorn", "--worker-class", "eventlet", "-w", "1", "-b", "0.0.0.0:5000", "--preload", "server.app:app"]
    
    environment:
      - LOCAL_SUBTENSOR_HOST=subtensor
    ports:
      # - 5000:5000
      - 8507-8515:8507-8515
      - 8080:8080
      - 8265:8265

    volumes:
      - ./bittensor/bittensor:/app/bittensor/bittensor
      - ./commune:/app/commune
      - ./.bittensor:/root/.bittensor
      - ./scripts:/app/scripts


    deploy:
      resources:
         reservations:
           devices:
           - driver: nvidia
             count: 'all'
             capabilities: [gpu]

    command: bash -c "chmod +x /app/scripts/*;/app/scripts/startup.sh;"

  